name: Join a QIIME 2 release

on:
  workflow_dispatch: {}

env:
  new_release: '2023.5'
  new_full_version: '2023.5.0'

jobs:
  join:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.INSTALL_WORKFLOWS_PAT }}
          path: ./current-repo

      # Where it checks out master we will probably end up checking out dev
      # since it sounds like we will be calling our main branches dev now.
      - name: branch repo
        shell: bash
        run: |
          cd ./current-repo
          git config --global user.name "q2d2"
          git config --global user.email "q2d2.noreply@gmail.com"
          git checkout -b ${{ env.new_release }}
          git commit --allow-empty -m "${{ env.new_release }}"
          git push --set-upstream origin ${{ env.new_release }}
          git checkout master
          git commit --allow-empty -m "${{ env.new_release }}"
          git tag -a ${{ env.new_full_version }}.dev0 -m "${{ env.new_full_version }}.dev0"
          git push --follow-tags

      # - name: tag dev
      # This will probably be another workflow that tags the release branch and
      # keeps the tag up to date
      # - name: tag release
