name: Join a QIIME 2 release

on:
  workflow_dispatch: {}

env:
  new_release: '2023.5'

jobs:
  join:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.INSTALL_WORKFLOWS_PAT }}
          path: ./current-repo

      # - id: empty-commit
      #   shell: bash
      #   run: |
      #     git commit --allow-empty -m "${{ env.new_release }}"

      - name: branch repo
        shell: bash
        run: |
          cd ./current-repo
          git config --global user.name "q2d2"
          git config --global user.email "q2d2.noreply@gmail.com"
          git checkout -b ${{ env.new_release }}
          git commit --allow-empty -m "${{ env.new_release }}"
          git push

      # - name: tag dev
      # This will probably be another workflow that tags the release branch and
      # keeps the tag up to date
      # - name: tag release
